# Generated by Django 6.0.5 on 2026-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='stock_date',
            field=models.DateField(default='2026-05-19'),
            preserve_default=False,
        ),
    ]
