# Generated by Django 6.0.5 on 2026-05-19 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_stockentry_invoice_number_stockentry_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='stock_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
