# Generated by Django 6.0.5 on 2026-05-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_stockentry_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_credit_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
