# Generated by Django 6.0.5 on 2026-05-17 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('nin', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('customer_type', models.CharField(choices=[('NORMAL', 'Normal Buyer'), ('RETAIL', 'Retailer'), ('WHOLESALE', 'Wholesaler')], default='NORMAL', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DepositPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('ONROUTE', 'On Route'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers_app.customer')),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers_app.deliverylocation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
