# Generated by Django 6.0.5 on 2026-05-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers_app', '0001_initial'),
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdelivery',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_app.sale'),
        ),
    ]
